title: Jens Pippig
email: jens.pippig@gmail.com
description: Ich bin ein leidenschaftlicher Mountainbike-Alpinist, Splitboarder und Abenteurer, der mit seiner Freundin im Van lebt. Auf meiner Seite bekommst du einen umfangreichen Einblick meiner Touren.
baseurl: "/blog"
url: "https://jenspippig.github.io"
twitter_username: ""
github_username: "jenspippig"

# Permalinks for posts
permalink: /:title/

# Exclude from processing
exclude:
  - .DS_Store
  - _site
  - Gemfile
  - Gemfile.lock